language: android
jdk: oraclejdk8
sudo: false

env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
  global:   #Optional
    - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins

android:
    update_sdk: true  #Check for the updates each time you run the build.
    components:
        - platform-tools
        - tools
        - build-tools-25.0.0    #Build tool version
        - android-25            #targate api version

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

        #system images for emulator
        - sys-img-armeabi-v7a-android-23
